Updated to pyenv, switch from env to install-*

diff --git a/test/all b/test/all
--- a/test/all
+++ b/test/all
@@ -1,10 +1,12 @@
 #!/usr/bin/bash
 
+TEST_PYTHON_VERSION=3.8.6
+
 install-aws-cli latest
 install-node latest
 install-yarn latest
 install-amplify-cli latest
-install-python 3
+install-python $TEST_PYTHON_VERSION
 install-ruby 3.1.2
 
 function fail {
@@ -15,6 +17,7 @@ function fail {
 
 . ~/.nvm/nvm.sh
 . ~/.rvm/scripts/rvm
+. ~/.bashrc.d/63-python
 
 . ~/.bashrc
 . ~/.profile
@@ -24,5 +27,7 @@ for COMM in aws node yarn python3 amplify ruby
 do
     type $COMM || fail $COMM failed to install
 done
+
+[[ "$(python3 --version)" == "Python ${TEST_PYTHON_VERSION}" ]] || fail "python3 failed to install"
 
 echo *** PASSED ***
